version: 2.0.{build}
skip_tags: true
image:
- Visual Studio 2017

services:
  - mssql2017

install:
  - 'ECHO Install: %APPVEYOR_PULL_REQUEST_NUMBER%,%APPVEYOR_REPO_BRANCH%,'
  - IF "%APPVEYOR_PULL_REQUEST_NUMBER%" == "" IF "%APPVEYOR_REPO_BRANCH%" == "master" SET CreateBinaries=true

configuration: Release

build_script:
  - ECHO Create databases
  - 'nuget.exe restore AsyncDataAdapter.sln'
  - 'msbuild.exe AsyncDataAdapter.msbuild /p:BuildNumber=%appveyor_build_version% /t:CI'

artifacts:
  - path: .\AsyncDataAdapter\**\*.nupkg
    name: NugetPackages

test: off
